Trigger print via state change
MatthewHerbst/react-to-print pull request #77
Opened 2018-12-15 13:55 UTC by steeevio

I was struggling to put the `<ReactToPrint>` within sibling / child components to the `<ComponentToPrint>` component. 

Maybe there is a better way of doing this but for me it seemed to make it more flexible if I could trigger print via state. then I can do it with a button from anywhere.

I just added a some of props `<ReactToPrint>` that allow the user to decide if they want to trigger from state
`useState={true}`

check the current print state - set to true to run print
`statePrint= {true}`

user should add a function that sets the print state back to false after use.
`handleStatePrintOff={this.handleStatePrintOff} `

2018-12-15 19:02 UTC, MatthewHerbst requested changes
Thanks for the PR! A few quick things first:

1. I left a bunch of style related comments on the PR that would be great if you could clean up
2. There shouldn't have been any changes to `package-lock.json` with this PR. You likely did an `npm install` instead of `npm ci`. Please do not commit an updated `package-lock.json` with this PR
3. Please add the new props to the `propTypes` definitions

I think overall what you are really trying to do is solve #68, which wants a way to print without having to use the button. While I think this approach is a good bandaid attempt to that before the work for #68 is complete, the issue is that if/when we do the work for #68, removing these changes would be a breaking change which should ideally be avoided. 

Would you be interested in working on #68 together rather than attempting this approach?

2018-12-15 19:02 UTC, MatthewHerbst commented on example/index.js
> +      print:false,
Nit:
```suggestion
      print: false,
```

2018-12-15 19:02 UTC, MatthewHerbst commented on example/index.js
> +  handleStatePrint = (e)=>{
Nit:

```suggestion
  handleStatePrint = (e) => {
```

2018-12-15 19:02 UTC, MatthewHerbst commented on example/index.js
> +  handleStatePrintOff = (e)=>{
Nit:
```suggestion
  handleStatePrintOff = (e) => {
```

2018-12-15 19:02 UTC, MatthewHerbst commented on example/index.js
> +    this.setState({print : false});
Nit:
```suggestion
    this.setState({ print: false });
```

2018-12-15 19:02 UTC, MatthewHerbst commented on example/index.js
> +    this.setState({print : true});
Nit:
```suggestion
    this.setState({ print: true });
```

2018-12-15 19:02 UTC, MatthewHerbst commented on example/index.js
> +          useState={false}
The default value of `useState` should be `false`, so you should never need to pass the prop with `false`

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +
Nit:
```suggestion
```

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +
Nit: please remove these extra newlines

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +        <div></div>
Please use `<div />`. Also, please make sure to add a semicolon after the closing `)`

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +
```suggestion
```

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +    }else{
```suggestion
    } else {
```

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +        <div></div>
Also, why did you choose to return an empty `div` here rather than `null`?

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +
Nit: please remove extra newlines

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +    if(this.props.useState === true){
Please destructure this prop above

2018-12-15 19:02 UTC, MatthewHerbst commented on src/index.js
> +      if(this.props.statePrint === true){
Please destructure this prop above

2018-12-16 20:43 UTC, steeevio commented on example/index.js
> +      print:false,
Hi, this was my first stab at a pull request, so thanks for taking the time over the feedback! I've a had a go at changing it as required - hopefully I got everything, if not let me know.

I'm new to react so not really sure how much help I can be in dealing with #68, I'm happy to try but honestly you might just end up spending more time explaining things to me.

2018-12-17 09:20 UTC, MatthewHerbst commented on example/index.js
> +      print:false,
Pretty great stab for your first PR, well done!

I actually think #68 doesn't have much to do with React - the goal is to take code that's currently baked into the component and move it into its own standalone JS. Then the React component can depend on it, and we can make it available to others. For example, a sample export might be:

```js
import { print } from 'react-to-print'
```

Then you could just call `.print(<someReactRef>|<someDOMNode>)`

That would solve what you are trying to do here, which is control when you print via external code. I'll take another look at it to see what a good path forward should be.

Do note I'm not the package owner, just an active contributor.

2018-12-17 19:28 UTC, gregnb commented
hey @MatthewHerbst really appreciate all your help. I've added push access for you

2018-12-17 20:11 UTC, MatthewHerbst commented
@gregnb thank you! Looking forward to getting some free time to address these issues :)

2018-12-17 21:32 UTC, steeevio commented on example/index.js
> +      print:false,
Thanks! I see what you mean, yes ultimately that seems like a better solution.

2019-01-04 08:50 UTC, MatthewHerbst commented
Going to close this in favor of #88 

@steeevio would love any feedback you have about that PR, which is still in early stages though the meat of it is done

2019-01-04 08:50 UTC, closed without merging